### ISSUE TITLE
Extra dot being added with SRV records 

### ISSUE THREAD

**Issue by rockpenguin** [octodns/octodns-dnsimple#19]
Hello!

It looks like there might be a bug similar to [832 in the OVH provider](https://github.com/octodns/octodns/issues/832 ) where it gets in the cycle of trying to fix the trailing dot at the end of the FQDN.

```
********************************************************************************
* mydomain.net.
********************************************************************************
* dnsimple (DnsimpleProvider)
*   Update
*     <SrvRecord SRV 3600, _imaps._tcp.mydomain.net., [''0 1 993 imap.fastmail.com..'']> ->
*     <SrvRecord SRV 3600, _imaps._tcp.mydomain.net., [''0 1 993 imap.fastmail.com.'']> (config)
*   Update
*     <SrvRecord SRV 3600, _submission._tcp.mydomain.net., [''0 1 587 smtp.fastmail.com..'']> ->
*     <SrvRecord SRV 3600, _submission._tcp.mydomain.net., [''0 1 587 smtp.fastmail.com.'']> (config)
*   Summary: Creates=0, Updates=2, Deletes=0, Existing Records=17
********************************************************************************
```

And if I remove the trailing dot from one of the FQDNs in the config, octoDNS throws an error:

```
  File "/Users/dave/src/infrastructure/dns/env/lib/python3.11/site-packages/octodns/record/__init__.py", line 153, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record _caldavs._tcp.mydomain.net.
  - SRV value "caldav.fastmail.com" missing trailing .
```

Similar to the OVH issue, if I remove the dot from the following line, then it works as hoped.

https://github.com/octodns/octodns-dnsimple/blob/93abd10c18a4cb06b832d3a26d632dd4f71b2fd8/octodns_dnsimple/__init__.py#L222

Happy to do a PR if needed. Thanks!

Dave

**Comment by yzguy** [comment]
Seems straight forward. I'm not familiar with DNSimple so I'm unsure if a target just being `.` is typical or really what the purpose of that is.

I know in the `octodns_constellix` provider we have an `_absolutize_value` method that handles detecting if the value is relative and then making it absolute. https://github.com/octodns/octodns-constellix/blob/main/octodns_constellix/__init__.py#L129-L135, so I suspect we need something like that as well here.
